Setup cleanup

diff --git a/virtual/setup b/virtual/setup
--- a/virtual/setup
+++ b/virtual/setup
@@ -1,9 +1,16 @@
 #!/bin/bash
 
-VIRTENABLED="$(egrep '(vmx|svm)' /proc/cpuinfo 2>&1 > /dev/null)"
+HYPERVISOR=""
+
+#Check user priviledges
+if [ "$EUID" -ne 0 ]; then
+    echo "Error: Setup requires root priviledges to run"
+    exit 1
+fi
 
 #Test Virtualization enabled
-if [ $? == 1 ]; then
+VIRTENABLED="$(egrep '(vmx|svm)' /proc/cpuinfo 2>&1 > /dev/null)"
+if [ "$VIRTENABLED" == 1 ]; then
     echo "Has hardware virtualization been enabled?"
     exit 1
 fi
@@ -38,6 +45,18 @@ else
     OS=$(uname -s)
     VER=$(uname -r)
 fi
+
+while [ "$HYPERVISOR" == "" ]; do
+    echo 'Would you like to use KVM or Xen as the hypervisor?... (Xen/KVM)'
+    read INPUT
+    if [ "$INPUT" == "Xen" ] || [ "$INPUT" == "xen" ]; then
+        $HYPERVISOR="XEN"
+    elif [ "$INPUT" == "KVM" ] || [ "$INPUT" == "kvm" ]; then
+        $HYPERVISOR="KVM"
+    else
+        echo "Error: Input invalid. Please choose between (Xen/KVM)"
+    fi
+done
 
 #Edit dnsmasq configuration file
 function edit_dnsmasq {
@@ -80,21 +99,29 @@ if [ "$OS" == "Debian GNU/Linux" ] && [ "$VER" == "10" ]; then
     eval "${PKGSTRING}${PKGS}"
     RESULT=$?
     if [ $RESULT == 0 ]; then
-      echo "All packaged installed"
+        if [ "$HYPERVISOR" == "XEN" ]; then
+            RESULT="$(apt install -y xen-system 2>&1 > /dev/null)"
+            if [ "$RESULT" = 0 ]; then
+                echo "All packaged installed"
+            else
+                echo "Error: Xen did not install correctly"
+            fi
+        fi
+        echo "All packaged installed"
     fi
 fi
 
 #Reboot necessary?
-USER="$(whoami)"
-SUDO=""
-if [ "$USER" == "root" ]; then
-    $SUDO = "sudo "
-fi
-XENINSTALL="$(${SUDO}xl list \| grep Domain-0)"
+XENINSTALL="$(xl list \| grep Domain-0)"
 if [ "$XENINSTALL" == "Domain-0" ]; then
-    echo 'Host already running as Domain-0'
+    echo 'Success: VM support installed'
+    exit 0
 else
-    echo 'Xen has been installed, restart and boot into Xen Hypervisor'
+    echo 'Success: VM support installed'
+    read -rsn1 "Would you like to reboot now?... (y/N)" INPUT
+    if [ "$INPUT" == "y" ] || [ "$INPUT" == "Y" ]; then
+        eval "reboot"
+        exit 0
+    fi
+    exit 0
 fi
-
-exit 0
